db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: qwerasdf
    MYSQL_DATABASE: enjoy_hq_dev
  restart: always
  ports:
    - "3307:3306"
  volumes:
    - "./init/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
  command: [ 'mysqld', '--init-file=/docker-entrypoint-initdb.d/setup.sql', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--max-allowed-packet=67108864' ]
